dist: trusty

language: python

python:
  - 3.6

git:
  depth: 1

cache:
  apt: true

install:
  - pip3 install pipenv
  - make init

script:
  - make gen
  - |
    # upgrade doc, but only when pushing to "master" branch
    # if [[ "$TRAVIS_BRANCH" == "dev" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
      ./publish.sh
    # fi