name: Publish docs via GitHub Pages
# from https://github.com/marketplace/actions/sphinx-to-github-pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        pip3 install pip-tools
        make init
    - name: Generate pages
      run: |
        ./deploy.sh
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages